/**
 * HTML Reporter Helper
 * 
 * Mochawesome integration helper.
 * The actual HTML report is generated by mochawesome via .mocharc.yml.
 * This utility provides helper functions for report management.
 */

const path = require('path');
const fs = require('fs');
const config = require('./configLoader');
const logger = require('./logger');

const reportDir = path.resolve(__dirname, '..', config.paths.reports);

/**
 * Ensure the reports directory exists.
 */
function ensureReportDir() {
  const mochawesomeDir = path.join(reportDir, 'mochawesome-report');
  if (!fs.existsSync(mochawesomeDir)) {
    fs.mkdirSync(mochawesomeDir, { recursive: true });
  }
  logger.info(`Report directory ready: ${mochawesomeDir}`);
}

/**
 * Get the path to the latest HTML report.
 * @returns {string|null} Path to the report or null if not found
 */
function getLatestReport() {
  const mochawesomeDir = path.join(reportDir, 'mochawesome-report');
  if (!fs.existsSync(mochawesomeDir)) return null;

  const files = fs.readdirSync(mochawesomeDir)
    .filter((f) => f.endsWith('.html'))
    .map((f) => ({
      name: f,
      path: path.join(mochawesomeDir, f),
      time: fs.statSync(path.join(mochawesomeDir, f)).mtime.getTime(),
    }))
    .sort((a, b) => b.time - a.time);

  return files.length > 0 ? files[0].path : null;
}

/**
 * Clean up old report files, keeping only the latest N reports.
 * @param {number} [keep=5] Number of reports to keep
 */
function cleanOldReports(keep = 5) {
  const mochawesomeDir = path.join(reportDir, 'mochawesome-report');
  if (!fs.existsSync(mochawesomeDir)) return;

  const files = fs.readdirSync(mochawesomeDir)
    .filter((f) => f.endsWith('.html') || f.endsWith('.json'))
    .map((f) => ({
      name: f,
      path: path.join(mochawesomeDir, f),
      time: fs.statSync(path.join(mochawesomeDir, f)).mtime.getTime(),
    }))
    .sort((a, b) => b.time - a.time);

  // Group by extension
  const htmlFiles = files.filter((f) => f.name.endsWith('.html'));
  const jsonFiles = files.filter((f) => f.name.endsWith('.json'));

  const toDelete = [...htmlFiles.slice(keep), ...jsonFiles.slice(keep)];
  toDelete.forEach((f) => {
    fs.unlinkSync(f.path);
    logger.info(`Cleaned old report: ${f.name}`);
  });
}

module.exports = { ensureReportDir, getLatestReport, cleanOldReports };
